services:
  kestra:
    image: kestra/kestra:latest
    pull_policy: always
    command: server local
    ports:
      - "8080:8080"
    user: root
    environment:
      JAVA_OPTS: "-XX:UseSVE=0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

volumes:
  kestra-data: